[project]
name = "my-clery"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "celery[redis]>=5.6.0",
    "django>=6.0",
    "python-decouple>=3.8",
]
